# Generated by Django 4.2.1 on 2023-05-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='consistency',
            field=models.CharField(choices=[('liquid', 'Liquid'), ('solid', 'Solid'), ('textile', 'Textile'), ('chemistry', 'Chemistry')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='item',
            name='usage_environment',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('bathroom', 'Bathroom'), ('bedroom', 'Bedroom'), ('livingroom', 'Living Room'), ('corridor', 'Corridor')], default='Unknown', max_length=20),
        ),
    ]
